---
resources:
- name: app
  type: git
  source:
    uri: https://github.com/axhi/not-your-pipeline.git
    paths: ["src"]
- name: ci
  type: git
  source:
    uri: https://github.com/axhi/not-your-pipeline.git
    paths: ["concourse"]

jobs:
- name: run-unit-test
  plan:
  - aggregate:
    - get: ci
    - get: app
      trigger: true
  - task: unit-test
    file: ci/tasks/run-unit-test.yml