---
jobs:
- name: run-unit-test
  public: true
  plan:
  - aggregate:
    - get: src
      trigger: true
    - get: concourse
  - task: unit-test
    file: concourse/tasks/run-unit-test.yml

resources:
- name: src
  type: git
  source:
    uri: https://github.com/axhi/not-your-pipeline
    paths: ["src"]
- name: concourse
  type: git
  source:
    uri: https://github.com/axhi/not-your-pipeline
    paths: ["concourse"]