---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
inputs:
  - name: ci
  - name: src
outputs:
  - name: build-output
run:
  path: ci/concourse/tasks/build-app.sh